### ISSUE TITLE
images

### ISSUE THREAD

**Issue by warahul** [submagr/MLT-Classifier#1]
![cycle](https://cloud.githubusercontent.com/assets/10486704/21241664/a747e9cc-c336-11e6-8c59-3303dd6b44ff.jpg)
![motorcycle](https://cloud.githubusercontent.com/assets/10486704/21241665/a74b7754-c336-11e6-8f06-e01c6912fd88.jpg)

**Comment by submagr** [comment]
These images are already present in results section
